import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'components/atoms/Badge/index': 'src/components/atoms/Badge/index.ts',
    'components/atoms/Button/index': 'src/components/atoms/Button/index.ts',
    'components/atoms/Chip/index': 'src/components/atoms/Chip/index.ts',
    'components/atoms/Field/index': 'src/components/atoms/Field/index.ts',
    'components/atoms/Icon/index': 'src/components/atoms/Icon/index.ts',
    'components/atoms/Image/index': 'src/components/atoms/Image/index.ts',
    'components/atoms/Input/index': 'src/components/atoms/Input/index.ts',
    'components/atoms/Link/index': 'src/components/atoms/Link/index.ts',
    'components/atoms/Loader/index': 'src/components/atoms/Loader/index.ts',
    'components/atoms/RichText/index': 'src/components/atoms/RichText/index.ts',
    'components/atoms/Select/index': 'src/components/atoms/Select/index.ts',
    'components/atoms/Switch/index': 'src/components/atoms/Switch/index.ts',
    'components/atoms/Textarea/index': 'src/components/atoms/Textarea/index.ts',
    'components/molecules/Accordion/index': 'src/components/molecules/Accordion/index.ts',
    'components/molecules/BottomSheet/index': 'src/components/molecules/BottomSheet/index.ts',
    'components/molecules/Breadcrumbs/index': 'src/components/molecules/Breadcrumbs/index.ts',
    'components/molecules/Card/index': 'src/components/molecules/Card/index.ts',
    'components/molecules/Banner/index': 'src/components/molecules/Banner/index.ts',
    'components/molecules/Carousel/index': 'src/components/molecules/Carousel/index.ts',
    'components/molecules/Drawer/index': 'src/components/molecules/Drawer/index.ts',
    'components/molecules/Dropdown/index': 'src/components/molecules/Dropdown/index.ts',
    'components/molecules/Filter/index': 'src/components/molecules/Filter/index.ts',
    'components/molecules/Language/index': 'src/components/molecules/Language/index.ts',
    'components/molecules/Modal/index': 'src/components/molecules/Modal/index.ts',
    'components/molecules/Showcase/index': 'src/components/molecules/Showcase/index.ts',
    'components/molecules/Marquee/index': 'src/components/molecules/Marquee/index.ts',
    'components/molecules/Snackbar/index': 'src/components/molecules/Snackbar/index.ts',
    'components/molecules/Table/index': 'src/components/molecules/Table/index.ts',
    'components/molecules/Timeline/index': 'src/components/molecules/Timeline/index.ts',
    'components/organisms/CookieConsent/index': 'src/components/organisms/CookieConsent/index.ts',
    'hooks/useDelayedUnmount/index': 'src/hooks/useDelayedUnmount/index.ts',
    'hooks/useDialogLayer/index': 'src/hooks/useDialogLayer/index.ts',
    'hooks/useDismissableLayer/index': 'src/hooks/useDismissableLayer/index.ts',
    'hooks/useFocusTrap/index': 'src/hooks/useFocusTrap/index.ts',
    'hooks/useMarquee/index': 'src/hooks/useMarquee/index.ts',
    'hooks/useMediaQuery/index': 'src/hooks/useMediaQuery/index.ts',
    'hooks/useMergedRef/index': 'src/hooks/useMergedRef/index.ts',
    'hooks/useScrollLock/index': 'src/hooks/useScrollLock/index.ts',
    'utils/cn/index': 'src/utils/cn/index.ts',
  },
  format: ['esm'],
  target: 'es2022',
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    '@inzumer/tokens',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
  ],
});
